//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Tienda.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO
    {
        public int CAR_ID { get; set; }
        public int CAR_ID_USUARIO { get; set; }
        public int CAR_ID_PRODUCTO { get; set; }
        public int CAR_CANTIDAD_X_PRODUCTO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
