//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Tienda.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public int DTCPA_ID { get; set; }
        public Nullable<int> DTCPA_ID_COMPRA { get; set; }
        public Nullable<int> DTCPA_ID_PRODUCTO { get; set; }
        public Nullable<int> DTCPA_CANTIDAD { get; set; }
        public Nullable<decimal> DTCPA_TOTAL { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
