//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Tienda.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.CARRITO = new HashSet<CARRITO>();
            this.DETALLE_COMPRA = new HashSet<DETALLE_COMPRA>();
        }
    
        public int PRD_ID { get; set; }
        public Nullable<int> PRD_ID_USUARIO_FK { get; set; }
        public string PRD_NOMBRE { get; set; }
        public string PRD_DESCRIPCION { get; set; }
        public Nullable<int> PRD_ID_MARCA_FK { get; set; }
        public Nullable<int> PRD_ID_CATEGORIA_FK { get; set; }
        public Nullable<decimal> PRD_PRECIO { get; set; }
        public Nullable<int> PRD_STOCK { get; set; }
        public Nullable<bool> PRD_ACTIVO { get; set; }
        public Nullable<System.DateTime> PRD_FECHA_REGISTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO> CARRITO { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPRA> DETALLE_COMPRA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
