//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Tienda.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_DIRECCION
    {
        public int DIR_ID { get; set; }
        public Nullable<int> DIR_ID_USUARIO_FK { get; set; }
        public string DIR_EXACTA { get; set; }
        public string DIR_PAIS { get; set; }
        public string DIR_PROVINCIA { get; set; }
        public string DIR_CANTON { get; set; }
        public string DIR_DISTRITO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
