//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Tienda.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_TELEFONO
    {
        public int TEL_ID { get; set; }
        public Nullable<int> TEL_ID_USUARIO_FK { get; set; }
        public string TEL_NUMERO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
