//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Tienda.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.BITACORA = new HashSet<BITACORA>();
            this.CARRITO = new HashSet<CARRITO>();
            this.COMPRA = new HashSet<COMPRA>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.USR_DIRECCION = new HashSet<USR_DIRECCION>();
            this.USR_TELEFONO = new HashSet<USR_TELEFONO>();
        }
    
        public int USR_ID { get; set; }
        public string USR_NOMBRE { get; set; }
        public string USR_IDENTIFICACION { get; set; }
        public string USR_CORREO { get; set; }
        public string USR_CONTRASENNA { get; set; }
        public Nullable<int> USR_ROL { get; set; }
        public Nullable<bool> USR_ACTIVO { get; set; }
        public Nullable<System.DateTime> USR_FECHA_REGISTRO { get; set; }
        public string USR_RECOVERY_TOKEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA> BITACORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO> CARRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_DIRECCION> USR_DIRECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_TELEFONO> USR_TELEFONO { get; set; }
    }
}
